brc_vis.settings:
  type: mapping
  label: 'BRC Visualisation settings'
  mapping:
    warehouse:
      type: mapping
      label: 'Warehouse settings'
      mapping:      
        url:
          type: text
          label: 'Warehouse URL:'
        id: 
          type: integer
          label: 'Website warehouse ID:'
        password:
          type: text
          label: 'Website warehouse password'
