brc_vis.settings:
  type: config_object
  label: 'BRC Visualisation settings'
  mapping:
    warehouse:
      type: mapping
      mapping:
        url:
          type: text
      type: mapping
      mapping:
        id: 
          type: integer
      type: mapping
      mapping:
        password:
          type: text
